services:
  bot:
    image: ghcr.io/maxaizer/hh-tg-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TOKEN: ${TOKEN}
    depends_on:
      - prometheus
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./logs:/app/logs
      - ./mydatabase.db:/app/mydatabase.db

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml

volumes:
  prometheus_data: