services:
  bot:
    image: ghcr.io/maxaizer/hh-tg-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    labels:
      - "env=${ENV}"
    depends_on:
      - prometheus
      - promtail
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./logs:/app/logs
      - ./mydatabase.db:/app/mydatabase.db

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    labels:
      - "env=${ENV}"
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  promtail:
    image: grafana/promtail:latest
    command: -config.expand-env=true -config.file=/etc/promtail/config.yml
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      - LOKI_URL=${LOKI_URL}
      - LOKI_USER=${LOKI_USER}
      - LOKI_PASSWORD=${LOKI_PASSWORD}
    labels:
      - "env=${ENV}"
    ports:
      - "127.0.0.1:9080:9080"

volumes:
  prometheus_data: