name: CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: |
        make test

    - name: Set up docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to docker hub with GitHub PAT
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercase docker image prefix
      run: echo "PREFIX_LC=${PREFIX,,}" >> ${GITHUB_ENV}
      env:
        PREFIX: '${{ github.repository_owner }}'

    - name: Build and push docker image
      id: build_image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        tags: ghcr.io/${{ env.PREFIX_LC }}/hh-tg-bot:latest
        push: true
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      DIR: "/bot"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Upload files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml,prometheus.yml,configs/**"
          target: "${{ env.DIR }}"

      - name: Create .env
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_TOKEN: ${{ secrets.TOKEN }}
          envkey_AI_KEY: ${{ secrets.AI_KEY }}
          envkey_LOKI_URL: ${{ secrets.LOKI_URL }}
          envkey_LOKI_USER: ${{ secrets.LOKI_USER }}
          envkey_LOKI_PASSWORD: ${{ secrets.LOKI_PASSWORD }}
          envkey_APP_NAME: hh-tg-bot
          fail_on_empty: true

      - name: Upload .env
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ".env"
          target: "${{ env.DIR }}"
          
      - name: Run bot
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.DIR }}
            docker compose pull
            docker compose down
            docker compose up -d
